import { useMemo, useState } from "react";
import type { BodyweightEntry } from "../domain/entities/BodyweightEntry";

type Range = "1M"|"3M"|"6M"|"1Y"|"ALL";
type Props = { entries: BodyweightEntry[]; unit:"KG"|"LB"; onAdd:(weight:number,date:string)=>Promise<void>; onDelete:(id:string)=>Promise<void> };
const days:Record<Exclude<Range,"ALL">,number>={"1M":31,"3M":93,"6M":186,"1Y":366};
export function WeightPage({entries,unit,onAdd,onDelete}:Props){
 const [range,setRange]=useState<Range>("3M"); const [weight,setWeight]=useState(""); const [date,setDate]=useState(new Date().toISOString().slice(0,10)); const [busy,setBusy]=useState(false);
 const filtered=useMemo(()=>{const sorted=[...entries].sort((a,b)=>a.recordedAt.localeCompare(b.recordedAt));if(range==="ALL")return sorted;const cutoff=Date.now()-days[range]*86400000;return sorted.filter(e=>new Date(e.recordedAt).getTime()>=cutoff)},[entries,range]);
 const latest=[...entries].sort((a,b)=>b.recordedAt.localeCompare(a.recordedAt))[0]; const first=filtered[0]; const change=latest&&first?latest.weight-first.weight:null;
 const pts=chartPoints(filtered);
 return <section><div className="section-heading"><div><p className="eyebrow">Bodyweight</p><h1 className="page-title">Weight</h1></div></div>
  <article className="card weight-log-card"><div><strong>Log weight</strong><p className="muted">Add today's weight or choose another date.</p></div><div className="weight-log-controls"><label>Weight<input type="number" min="1" step="0.1" value={weight} onChange={e=>setWeight(e.target.value)} placeholder={unit}/></label><label>Date<input type="date" value={date} onChange={e=>setDate(e.target.value)}/></label><button className="primary" disabled={busy||!Number(weight)} onClick={async()=>{setBusy(true);try{await onAdd(Number(weight),date);setWeight("")}finally{setBusy(false)}}}>Log weight</button></div></article>
  <div className="weight-stats"><article className="card"><span>Current</span><strong>{latest?`${latest.weight.toFixed(1)} ${unit.toLowerCase()}`:"—"}</strong></article><article className="card"><span>Change</span><strong>{change==null?"—":`${change>0?"+":""}${change.toFixed(1)} ${unit.toLowerCase()}`}</strong></article></div>
  <article className="card weight-chart-card"><div className="weight-chart-head"><h2>Weight trend</h2><div className="range-tabs">{(["1M","3M","6M","1Y","ALL"] as Range[]).map(r=><button className={range===r?"active":""} onClick={()=>setRange(r)} key={r}>{r==="ALL"?"All":r}</button>)}</div></div>{pts.length<2?<div className="weight-empty">Log at least two weights to see your trend.</div>:<svg className="weight-chart" viewBox="0 0 700 260" role="img" aria-label="Bodyweight over time"><polyline points={pts.map(p=>`${p.x},${p.y}`).join(" ")} fill="none" stroke="currentColor" strokeWidth="4" strokeLinejoin="round" strokeLinecap="round"/>{pts.map((p,i)=><circle key={i} cx={p.x} cy={p.y} r="5" fill="currentColor"><title>{p.label}</title></circle>)}</svg>}</article>
  <article className="card weight-history"><h2>Recent entries</h2>{entries.length===0?<p className="muted">No weights logged yet.</p>:[...entries].sort((a,b)=>b.recordedAt.localeCompare(a.recordedAt)).slice(0,20).map(e=><div className="weight-history-row" key={e.id}><div><strong>{e.weight.toFixed(1)} {unit.toLowerCase()}</strong><span>{new Date(e.recordedAt).toLocaleDateString()}</span></div><button className="icon-button" aria-label="Delete weight" onClick={()=>void onDelete(e.id)}>×</button></div>)}</article>
 </section>
}
function chartPoints(entries:BodyweightEntry[]){if(entries.length<2)return [];const values=entries.map(e=>e.weight),min=Math.min(...values),max=Math.max(...values),pad=Math.max((max-min)*.25,.5),lo=min-pad,hi=max+pad;return entries.map((e,i)=>({x:30+i*(640/(entries.length-1)),y:230-200*((e.weight-lo)/(hi-lo)),label:`${e.weight.toFixed(1)} · ${new Date(e.recordedAt).toLocaleDateString()}`}));}
